name: Elliott Hauser - since 1983
highlighter: pygments

title: Elliott Hauser
subtitle: doing stuff since 1983

sections:
  - bio

special-layouts:
  - "tools"

timezone: America/New_York

github: http://github.com/eah13
twitter: http://twitter.com/@hauspoor
linkedin: http://linkedin.com/in/elliotthauser
other_site: http://trinket.io