name: Elliott Hauser - since 1983
pygments: true

title: Elliott Hauser
subtitle: doing stuff since 1983

sections:
  - bio

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

timezone: America/New_York